# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecosystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ecosystem(object):
    def setupUi(self, main_ui):
        main_ui.setObjectName("main_ui")
        main_ui.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(main_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.wdgt_main = QtWidgets.QWidget(self.centralwidget)
        self.wdgt_main.setGeometry(QtCore.QRect(30, 20, 741, 441))
        self.wdgt_main.setObjectName("wdgt_main")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 470, 711, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_gen = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_gen.setObjectName("btn_gen")
        self.horizontalLayout.addWidget(self.btn_gen)
        self.btn_step = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_step.setObjectName("btn_step")
        self.horizontalLayout.addWidget(self.btn_step)
        self.btn_simu = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_simu.setObjectName("btn_simu")
        self.horizontalLayout.addWidget(self.btn_simu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_quit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        main_ui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_ui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuSimulation = QtWidgets.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menumenu3 = QtWidgets.QMenu(self.menubar)
        self.menumenu3.setObjectName("menumenu3")
        main_ui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_ui)
        self.statusbar.setObjectName("statusbar")
        main_ui.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(main_ui)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(main_ui)
        self.actionQuit.setObjectName("actionQuit")
        self.actionitem1 = QtWidgets.QAction(main_ui)
        self.actionitem1.setObjectName("actionitem1")
        self.menuSimulation.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionQuit)
        self.menumenu3.addAction(self.actionitem1)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menumenu3.menuAction())

        self.retranslateUi(main_ui)
        self.btn_quit.clicked.connect(main_ui.close)
        self.actionQuit.triggered.connect(main_ui.close)
        QtCore.QMetaObject.connectSlotsByName(main_ui)

    def retranslateUi(self, main_ui):
        _translate = QtCore.QCoreApplication.translate
        main_ui.setWindowTitle(_translate("main_ui", "Ecosystem"))
        self.btn_gen.setText(_translate("main_ui", "Generate"))
        self.btn_step.setText(_translate("main_ui", "Step"))
        self.btn_simu.setText(_translate("main_ui", "Simulate"))
        self.btn_quit.setText(_translate("main_ui", "Quit"))
        self.menuSimulation.setTitle(_translate("main_ui", "Simulation"))
        self.menuFile.setTitle(_translate("main_ui", "File"))
        self.menumenu3.setTitle(_translate("main_ui", "menu3"))
        self.actionSettings.setText(_translate("main_ui", "Settings"))
        self.actionQuit.setText(_translate("main_ui", "Quit"))
        self.actionQuit.setShortcut(_translate("main_ui", "Ctrl+Q"))
        self.actionitem1.setText(_translate("main_ui", "item1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_ui = QtWidgets.QMainWindow()
    ui = Ui_ecosystem()
    ui.setupUi(main_ui)
    main_ui.show()
    sys.exit(app.exec_())
